name: County cases
on:
  schedule:
    - cron: '10 */4 * * *'
  workflow_dispatch:

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: run
        name: Run
        uses: ./.github/actions/scrape
        with:
          module: county-cases
